### ISSUE TITLE
Provide Docker image 

### ISSUE THREAD

**Issue by jw-s** [e-travel/cloudwatchlogsbeat#10]
Any chance of providing a Docker image for this beat?

**Comment by LundkvistViktor** [comment]
This would indeed be very nice, as running this in fargate makes perfect sense.

**Comment by kkentzo** [comment]
Will try to provide something.

**Comment by kkentzo** [comment]
We now have a `Dockerfile` in the project courtesy of @rms1000watt. 

Next step would be to provide an official image probably using the Travis pipeline.

**Comment by tedder** [comment]
Linking #12 for context.

**Comment by dimuskin** [comment]
@jw-s you can use this https://hub.docker.com/r/dimuskin/cloudwatchlogsbeat/
based on official Dockerfile from here: https://github.com/e-travel/cloudwatchlogsbeat/blob/master/Dockerfile 

only difference, I added `CMD ["/cloudwatchlogsbeat", "-e"]
` instead `CMD ["/cloudwatchlogsbeat"]  for easy debugging.
`
