### ISSUE TITLE
Update to latest Beats

### ISSUE THREAD

**Issue by sourabh10995** [e-travel/cloudwatchlogsbeat#11]
Will there be support for cloud ID?

**Comment by kkentzo** [comment]
@sourabh10995 I understand that you're referring to [this feature](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-cloud-id.html). Would you be able/willing to work on this? Pull requests are welcome you know ;-) If not, that's fine too. We'll look into upgrading the beats lib in any case.

**Comment by sourabh10995** [comment]
@kkentzo I would be glad to work on this but sadly I have no experience with Go. But I have found a workaround to use CloudID. CloudID is a base64 encoded string of Elasticsearch and Kibana hostnames so you can manually decode it and use it in the hosts field in your yml file.

Also, there was a breaking change since Elasticsearch 6.0 regarding the removal of mapping types. You can find more info [here](https://medium.com/@federicopanini/elasticsearch-6-0-removal-of-mapping-types-526a67ff772).

**Comment by kkentzo** [comment]
The beat is now updated to the latest version of libbeat (see #26)
