### ISSUE TITLE
elasticsearch 7

### ISSUE THREAD

**Issue by dustintenney** [e-travel/cloudwatchlogsbeat#25]
Any chance to get an update so it works with elastic 7.  Might just need a new template.

**Comment by kkentzo** [comment]
I have put some work on this (branch is libbeat-updates); the results are in PR #26 . 

@dustintenney : Would it be possible to test it before I merge it to the master branch and cut a new version?

**Comment by kkentzo** [comment]
I have now tested this locally and the updated version works. I will go ahead with merging #26 and release a new version.
