### ISSUE TITLE
Go Modules

### ISSUE THREAD

**Issue by CpuID** [e-travel/cloudwatchlogsbeat#28]
Now that Go Modules are becoming more mainstream/out of the box supported, would be nice to migrate off Glide :)

**Comment by kkentzo** [comment]
Yep makes sense. I made an attempt a few months ago but it didn't go smoothly. I'll try to have a go at it again and report back.

**Comment by kkentzo** [comment]
I have done [some work](https://github.com/e-travel/cloudwatchlogsbeat/tree/switch-to-go-modules) here - my understanding so far is that, unfortunately, the beats library does not play that nicely with go modules (yet?). Will keep on trying though - any help appreciated.

**Comment by kkentzo** [comment]
This has now been done, courtesy of @wernerb (#34).
