### ISSUE TITLE
feat req: put s3 registry files at prefix

### ISSUE THREAD

**Issue by tedder** [e-travel/cloudwatchlogsbeat#3]
It'd be nice to not only specify a bucket, but also specify a prefix where the registry files are kept.

**Comment by kkentzo** [comment]
Implemented in 890b55c5b960fc9263588df2a252a38f302557e7

**Comment by tedder** [comment]
@kkentzo are you working on a release?

**Comment by kkentzo** [comment]
Yes

**Comment by kkentzo** [comment]
New beat version with the requested feature [has been released](https://github.com/e-travel/cloudwatchlogsbeat/releases/tag/v1.2.0)
