### ISSUE TITLE
Include AWS CloudWatch Log Group Tags

### ISSUE THREAD

**Issue by calvinbui** [e-travel/cloudwatchlogsbeat#30]
Feature Request:

It is possible to add tags onto CloudWatch Log Groups: https://docs.aws.amazon.com/cli/latest/reference/logs/tag-log-group.html

Is it possible for these to be included in the log event sent to ES?

**Comment by kkentzo** [comment]
Looks doable (and [supported by sdk](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatchlogs/#CloudWatchLogs.ListTagsLogGroup)).

Would a comma-separated tag list do?

**Comment by calvinbui** [comment]
I believe functionbeat creates a new label for each tag like `tag.<key>`
