### ISSUE TITLE
Question: Amazon Kinesis

### ISSUE THREAD

**Issue by MartinLoeper** [e-travel/cloudwatchlogsbeat#8]
I searched for a way to get my vpc flow log data into elasticsearch and just stumbled across [cloudwatch-logs-subscription-consumer](https://github.com/amazon-archives/cloudwatch-logs-subscription-consumer).

You write in the description that cloudwatchlogsbeat's "operation is subject to AWS limitations and throttling policies".

Out of pure curiosity: Would this throttling policies also apply when using [Amazon Kinesis](https://aws.amazon.com/de/kinesis/) - as cloudwatch-logs-subscription-consumer does?

**Comment by kkentzo** [comment]
I am not familiar with the particular project you are referring to but kinesis is certainly subject to [usage limits](https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html).

**Comment by MartinLoeper** [comment]
Yes, of course there are usage limits.

However, I think the Amazon Kinesis approach might suit better for log streaming than using the CloudWatch logs apis directly.
That is because the [CloudWatch Logs Limits](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html) look quite restrictive to me, compared to the Kinesis usage limits.

**Comment by kkentzo** [comment]
OK, now I see you point. Yes, I guess what you describe is a valid approach as well although I am not sure how the pricing aspect would play out in this case. Another approach could be to bypass the beat alltogether and work with [logstash input plugins](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kinesis.html).
